jobs:
  github-pages:
    concurrency: github-pages
    if: ${{ github.repository == 'emichael/dslabs' }}
    name: Deploy to GitHub pages
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-gems-${{ hashFiles('./www/Gemfile.lock') }}
        path: ./www/vendor/bundle
        restore-keys: '${{ runner.os }}-gems-

          '
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: adopt
        java-version: '17'
    - continue-on-error: true
      run: make www/javadoc/
    - continue-on-error: true
      uses: helaili/jekyll-action@v2
      with:
        jekyll_build_options: --baseurl /dslabs/
        jekyll_src: ./www
        target_branch: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}
name: Github Pages
on:
  repository_dispatch:
    types: trigger-ga___github-pages.yml
