jobs:
  check-format:
    name: Check formatting
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: adopt
        java-version: '17'
    - continue-on-error: true
      run: make check-format
  publish:
    concurrency: publish-handout
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository
      == 'emichael/dslabs' }}
    name: Publish handout
    needs: test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: adopt
        java-version: '17'
    - continue-on-error: true
      run: make build/handout/
    - continue-on-error: true
      run: 'cd build/handout/


        git init -b handout


        git config user.name "${GITHUB_ACTOR}"

        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"


        git add .


        git commit -m "Committing built handout"


        git push -f "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        handout:handout


        rm -rf .git

        cd ../..

        '
  test:
    name: Tests - Java version ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: adopt
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      run: make dependencies
    - continue-on-error: true
      run: make all
    - continue-on-error: true
      run: make test
    strategy:
      matrix:
        java:
        - '17'
        - '20'
        - '21'
name: Continuous Integration
on:
  repository_dispatch:
    types: trigger-ga___test-publish.yml
